version: "3.7"
services:
  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - "${PWD}/db-data:/var/lib/postgresql/data"

  local-runner:
    image: amazon/mwaa-local:2_10_3
    restart: always
    depends_on:
      - postgres
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - "${PWD}/../dags/cep/dags:/usr/local/airflow/dags"
      - "${PWD}/../dags/.airflowignore:/usr/local/airflow/dags/.airflowignore"
      - "${PWD}/../dags/cep/hoarder:/usr/local/airflow/dags/cep/hoarder"
      - "${PWD}/../dags/cep/CARD:/usr/local/airflow/dags/cep/CARD"
      - "${PWD}/../requirements.txt:/usr/local/airflow/requirements/requirements.txt"
      - "${PWD}/startup_script:/usr/local/airflow/startup"
      - "${PWD}/plugins:/usr/local/airflow/plugins"
    ports:
      - "8080:8080"
    command: local-runner
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3
    env_file:
      - ./config/.env.localrunner
